fabrikAuth/urls.py
# import json
import os

from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from citizens import views as citizens_views
from citizens.admin import UserLoginForm

# @login_required()
# def userdata(request):
#     user = request.user
#     return HttpResponse(
#         json.dumps({
#             'username': user.username
#         }),
#         content_type='application/json'
#     )


urlpatterns = []


# Note: MODE must not be set, for setupping cachefiles within Dockerfile...
MODE = os.environ.get('MODE')

if not MODE or MODE == "OAUTH":
    # only expose what is necessary for the public!!!
    urlpatterns += [
        path("o/", include('oauth2_provider.urls', namespace='oauth2_provider')),

        # path(r"accounts/emailupdate", citizens_views.AccountsEmailUpdate.as_view(), name="emailupdate"),
        path(r"accounts/emailupdate", csrf_exempt(citizens_views.profileUpdateView), name="emailupdate"),
        path(
            'accounts/login',
            citizens_views.LoginView.as_view(
                template_name="citizens/login.html",
                authentication_form=UserLoginForm
                ),
            name='login')
    ]

if not MODE or MODE != "OAUTH":
    # Do not load oauth functionality here...
    urlpatterns += [
        path('admin/', admin.site.urls),
        # path("o/", include('oauth2_provider.urls', namespace='oauth2_provider')),
        # path('userdata', userdata, name='userdata'),
        path('accounts/', include('django.contrib.auth.urls')),
        path('mailing', include('massmailer.urls')),  # massmailer
    ]

citizens/models.py
from django.conf import settings
from citizens.lib.chacha20 import decryptToken, set_new_token, validtoken
from django.db import models

# Create your models here.
# https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#authentication-backends
from django.contrib.auth.models import AbstractUser

# TODO https://schinckel.net/2019/09/18/postgres-enum-types-in-django/
# => for massmailer permissions query => register_enum


class User(AbstractUser):
    class Meta:
        db_table = 'auth_user'

    token = models.CharField(
        # db_column='token',
        max_length=300,
        unique=True,
        null=True,
        blank=True)

    import_bulk = models.CharField(
        max_length=100,
        unique=False,
        null=True,
        blank=True)

    extra = models.CharField(
        max_length=300,
        null=True,
        blank=True)

    @property
    def deccryptedtoken(self):

        try:
            token = decryptToken(self.token, '0000', settings, returnAsUTF8=True)
        except Exception:
            token = None
        
        # is the token still valid? (If not, then, create a new one...)
        # create new token:
        if not validtoken(token, settings):
            token = set_new_token(self.username)
            assert validtoken(token, settings)
        
            self.token = decryptToken(token, '0000', settings, inputAsUTF8=True)
            assert decryptToken(self.token, '0000', settings, returnAsUTF8=True) == token
            self.save()
            
        assert token
        return token

    @property
    def tokenurl(self):

        return settings.TOKEN_LOGIN_URL % self.deccryptedtoken

    USERNAME_FIELD = 'username'
    # REQUIRED_FIELDS = ['email']

citizens/views.py
import logging
import json
from django.http.response import Http404, HttpResponseForbidden
from jsonview.decorators import json_view
# from jsonview.decorators import json_view
from jsonview.views import JsonView
from django.http import HttpResponse

from django.contrib.auth import views as django_views
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View

from citizens.admin import JWTEmailUpdateForm
from citizens.AuthBackend import JWTProtectedResourceMixin

log = logging.getLogger("oauth2_provider")


class LoginView (django_views.LoginView):
    """ Login View """
    # Not used, since citizens use oAuth Login View...
    pass


@json_view
def profileUpdateView(request):
    # STORE EMAILADRESS
    # assert request.user
    # assert request.client.client_secret
    try:
        request.POST = json.loads(request.body)
    except json.decoder.JSONDecodeError:
        raise Http404

    form = JWTEmailUpdateForm(request.user, request.POST)
    jwtauth = JWTProtectedResourceMixin(form)
    authenticated = jwtauth.dispatch(request)
    if not authenticated:
        return HttpResponseForbidden()

    # print(request.user)
    # Submit userprofile
    #  or form.data.get('lastname')
    form = JWTEmailUpdateForm(request.user, request.POST)
    if form.data.get('email'):
        if form.is_valid() and form.cleaned_data.get('email'):
            form.save()
            return HttpResponse(
                content=json.dumps({'ok': True}),
                status=200,
                content_type="application/json"
            )
        else:
            return HttpResponse(
                status=404,
                content_type="application/json"
            )


    # Just read current profile data
    return HttpResponse(
        content=json.dumps({
            'email': request.user.email
            # 'last_name': request.user.last_name,
            # 'extra': request.user.extra,
            # 'first_name': request.user.first_name
        }),
        status=200,
        content_type="application/json"
    )

templates/ARCHIV/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Password reset complete{% endblock %}

{% block content %}
<h1>Password reset complete</h1>
<p>Your new password has been set. You can log in now on the <a href="{% url 'login' %}">log in page</a>.</p>
{% endblock %}

templates/ARCHIV/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}Enter new password{% endblock %}
{% load i18n %}

{% block content %}

{% if validlink %}

<h1>Set a new password!</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Change my password">
</form>

{% else %}

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}
{% endblock %}

templates/ARCHIV/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Email Sent{% endblock %}

{% block content %}
  <h1>Check your inbox.</h1>
  <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
{% endblock %}

templates/ARCHIV/password_reset_form.html
{% extends 'base.html' %}

{% block title %}Forgot Your Password?{% endblock %}

{% block content %}
  <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <base href='' />
    <title>{% block title %}{% endblock %}</title>
    <meta charset=utf-8>
    <meta name="description" content="Demokratiefabrik Authentifizierung">
    <meta name=format-detection content="telephone=no">
    <meta name=msapplication-tap-highlight content=no>
    <meta name=viewport content="user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width">
    <link rel="icon" type="image/png" sizes="128x128" href="https://www.demokratiefabrik.ch/icons/favicon-128x128.png">
    <link rel="icon" type="image/png" sizes="96x96" href="https://www.demokratiefabrik.ch/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://www.demokratiefabrik.ch/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://www.demokratiefabrik.ch/icons/favicon-16x16.png">
    <!-- first load django static tag. -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.demokratiefabrik.min.css' %}">
</head>

<body>
    <div id=q-app>
        <header data-v-6da80873="" class="q-header q-layout__section--marginal text-primary shadow-1 bg-white">
            <div data-v-6da80873="" align="center" style="min-height: 40px;">
                <div data-v-6da80873="" role="img" class="q-img overflow-hidden"
                    style="max-width: 241px; max-height: 120px;">
                    <div style="padding-bottom: 100%;"></div>
                    <div class="q-img__image absolute-full"
                        style="background-size: cover; background-position: 50% 50%; background-image: url(&quot;{% static 'img/logoweb.png' %}&quot;);">
                    </div>
                    <div class="q-img__content absolute-full"></div>
                </div>
            </div>
        </header>
        <main style="margin-left:30%;">
            {% block content %}{% endblock %}
        </main>
    </div>
</body>

</html>

templates/citizens/login.html
{% extends 'base.html' %}
{% comment %}
https://stackoverflow.com/questions/55369645/how-to-customize-default-auth-login-form-in-django
{% endcomment %}
{%block title %}Anmeldung Demokratiefabrik{% endblock %} {% block content %}

<br>
<div style=" margin:1em;">
    <form method="post" style="max-width:400px; width:80%;">{% csrf_token %}
        <h1>Anmeldung zur Demokratiefabrik</h1>


        {% if form.non_field_errors %}

        <p style="color:red">
            Beim Login ist ein Fehler aufgetreten. Überprüfen Sie bitte, ob alle Angaben richtig erfasst sind.
            <br>
        </p>
        {% endif %}

        {% if form.token.initial %}

        <div class="fieldWrapper">
            {{ form.token.errors }}
            <p>
                Klicken Sie auf 'Login' um sich automatisch einzuloggen.
                <input type="hidden" name="token" maxlength="150" id="id_username" value="{{ form.token.initial }}">
                <input type="hidden" name="username" autocapitalize="none" maxlength="150" required="" id="id_username"
                    value="NONEMPTY">
                <input type="hidden" name="password" value="NONEMPTY" />
            </p>
        </div>

        {% elif form.ltoken.initial and not form.non_field_errors %}

        <div class="fieldWrapper">
            <p>
                Klicken Sie auf 'Login' um sich automatisch einzuloggen.
                <input type="hidden" name="ltoken" maxlength="150" id="id_username" value="{{ form.ltoken.initial }}">
                <input type="hidden" name="username" autocapitalize="none" maxlength="150" required="" id="id_username"
                    value="NONEMPTY">
                <input type="hidden" name="password" value="NONEMPTY" />
            </p>
        </div>

        {% else %}

        <div class="fieldWrapper">

            <p>
                {{ form.username.errors }}
                <label style="display: inline-block; width: 150px;" for="id_username">PIN (5 Zahlen)</label>

                {% if form.username.value %}
                <input type="text" value="{{form.username.value }}" name="username" maxlength="150" required
                    id="id_username">
                {% else %}
                <input type="text" name="username" maxlength="150" required id="id_username">
                {% endif %}
            </p>
            <p>

                {{ form.password.errors }}
                <label style="display: inline-block; width: 150px;" for="{{ form.password.id_for_label }}">
                    Passwort (Grossbuchstaben):</label> {{ form.password }}
            </p>
            <br>
        </div>
        {% endif %}
</div>



<div>
    <input type="hidden" name="next" value="{{ next }}" />

    <button type="submit">Login</button>&nbsp;&nbsp;&nbsp;<a href='https://www.demokratiefabrik.ch'>Abbrechen</a>
</div>
</form>
<br><br>
<p style="max-width:400px; width:80%;">
    Sie finden diese Angaben auf dem Einladungsbrief, den wir Ihnen zugesendet haben.
</p>

</div>
{% endblock %}

{% comment %}
<!-- Ist der
        Einladungsbrief nicht mehr auffindbar, dann können Sie sich via E-Mail <a
            href="mailto:demokratiefabrik.ipw@unibe.ch">E-mail</a> bei uns melden. Dabei muss
        zwingend die E-Mail-Adresse angeben werden, welche Sie beim ersten Besuch auf der Plattform hinterlegt haben. -->

{{ form.errors }}

ORIGINAL {{ form.as_p }} DUMMY USERNAMEddd
<input type="hidden" name="username" autocapitalize="none" maxlength="150" required="" id="id_username"
    value="NONEMPTY">
<div class="fieldWrapper">
    <label style="display: inline-block; min-width: 150px;" for="{{ form.token.id_for_label }}">Persönlicher PIN:
    </label> {{ form.token }}
    <input type="text" name="token" autofocus="" autocapitalize="none" autocomplete="token" maxlength="150" required=""
        id="id_token" data-kpxc-id="id_token">
    <input type="hidden" name="password" value="demokratiefabrik" />
    {% endcomment %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}